// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF.Model
{
    public partial class Image
    {
        public int ImageId { get; set; }
        public string Title { get; set; }
        public byte[] Data { get; set; }
        public int ItemId { get; set; }

        public virtual Item Item { get; set; }
    }
}