// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF.Model
{
    public partial class Item
    {
        public int ItemId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string PictureUrl { get; set; }
        public DateTime? FindingDate { get; set; }
        public DateTime? LossDate { get; set; }
        public int AdvertisementId { get; set; }
        public int CategoryId { get; set; }

        public virtual Advertisement Advertisement { get; set; }
        public virtual Category Category { get; set; }
    }
}