// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF.Model
{
    public partial class Message
    {
        public int MessageId { get; set; }
        public string Content { get; set; }
        public int RecieverId { get; set; }
        public DateTime SendDateTime { get; set; }
        public int IsRead { get; set; }
        public DateTime? ReadDateTime { get; set; }
        public int AccountId { get; set; }

        public virtual Account Account { get; set; }
    }
}